### ISSUE TITLE
Signatur parse error and ClassFormatError since 2.4.2

### ISSUE THREAD

**Issue by languitar** [Anamorphosee/stacktrace-decoroutinator#34]
Since 2.4.2, stacktrace decoroutinator does not work in our project anymore. Most tests don't run successfully with either one of the two errors shown below:

```
Method getA in class org/modelix/model/IKeyValueStore has illegal modifiers: 0x101A
java.lang.ClassFormatError: Method getA in class org/modelix/model/IKeyValueStore has illegal modifiers: 0x101A
	at org.modelix.model.ModelFacade.newLocalTree(ModelFacade.kt:26)
```

```
Signature Parse error: expected '<' or ';' but got  
	Remaining input:  user-specific event if logged in$2;
java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected '<' or ';' but got  
	Remaining input:  user-specific event if logged in$2;
	at java.base/sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at java.base/sun.reflect.generics.parser.SignatureParser.parsePackageNameAndSimpleClassTypeSignature(SignatureParser.java:337)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:304)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:277)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:469)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:438)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:427)
	at java.base/sun.reflect.annotation.AnnotationParser.lambda$parseClassArray$0(AnnotationParser.java:718)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArrayElements(AnnotationParser.java:746)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:717)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:530)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:352)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:282)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:4125)
	at java.base/java.lang.Class.annotationData(Class.java:4114)
	at java.base/java.lang.Class.getDeclaredAnnotation(Class.java:4053)
	at dev.reformator.stacktracedecoroutinator.common.internal.TransformedClassesRegistry.registerTransformedClass(transformedClassesRegistry.kt:39)
	at dev.reformator.stacktracedecoroutinator.common.internal.Provider.registerTransformedClass(provider-impl.kt:42)
	at dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorProviderApiKt.registerTransformedClass(provider-api.kt:56)
```

2.4.1 worked perfectly well.

**Comment by Anamorphosee** [comment]
Hi, @languitar 
Could you please provide your JDK version?

**Comment by Anamorphosee** [comment]
@languitar I have determine and resolve the first issue (with illegal modifiers: 0x101A).
But the second one seems very strange and I have some suspicions that it isn't related to Decoroutinator.

Could you please do some actions to check it:
1. find a class which throws the exception (in the stack trace it have to be before frame `dev.reformator.stacktracedecoroutinator.provider.DecoroutinatorProviderApiKt.registerTransformedClass`)
2. start your app without Decoroutinator and call `<class from paragraph 1.>::class.java.getDeclaredAnnotations()` to check if the exception has disappeared or not?

**Comment by languitar** [comment]
Could the second issue be related to using jacoco?

The other things I'll check tomorrow. Just for reference, the affected test methods has this signature:

```kotlin
    @Test
    fun `returns user-specific event if logged in`() {
```

**Comment by Anamorphosee** [comment]
I have reproduce it.
And seems it's a bug in Kotlin compiler inself
https://youtrack.jetbrains.com/issue/KT-25337/GenericSignatureFormatError-when-using-Java-reflection-on-a-declaration-named-with-spaces

**Comment by languitar** [comment]
Thanks for the quick response! 7 years old big in the compiler... Why didn't this trigger prior to 2.4.2?

**Comment by Anamorphosee** [comment]
>Why didn't this trigger prior to 2.4.2?

Because in 2.4.2 was implemented a new feature - tail calls deoptimization. And it requires a little more classes to reflect. But I'm right now working on a workaround to fix that. So, the issue will be fixed in the next release

**Comment by Anamorphosee** [comment]
fixed in 2.4.4

**Comment by languitar** [comment]
Thanks again for the quick fix. Unfortunately, the new release doesn't seem to have covered all issues.

One situation I can see is the use of multi-word method names inside `@Nested` inner classes in JUnit, which is triggering a GenericSignatureFormatError again:

```kotlin
class SomeTest {

    @Nested
    inner class Foo {
        @Test
        fun `multiple words`() {}
    }
}
```

The other issue I see is that with bumping to 2.4.4, we suddenly have unit tests that hang forever. Oddly, I am unable to suspend the test in the debugger to see what is actually causing this.

**Comment by Anamorphosee** [comment]
>One situation I can see is the use of multi-word method names inside @Nested inner classes in JUnit, which is triggering a GenericSignatureFormatError again:

Could you please provide a stack trace with GenericSignatureFormatError?

**Comment by languitar** [comment]
I can't provide the full stacktrace due to privacy reasons, but I hope the anonymized version is still sufficient. Even with the weird test names this still fails:

```
Signature Parse error: expected '<' or ';' but got  
	Remaining input:  something else$1$1;
java.lang.reflect.GenericSignatureFormatError: Signature Parse error: expected '<' or ';' but got  
	Remaining input:  something else$1$1;
	at java.base/sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at java.base/sun.reflect.generics.parser.SignatureParser.parsePackageNameAndSimpleClassTypeSignature(SignatureParser.java:337)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseClassTypeSignature(SignatureParser.java:304)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:283)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:277)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:469)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:438)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:427)
	at java.base/sun.reflect.annotation.AnnotationParser.lambda$parseClassArray$0(AnnotationParser.java:718)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArrayElements(AnnotationParser.java:746)
	at java.base/sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:717)
	at java.base/sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:530)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:352)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:282)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.Class.createAnnotationData(Class.java:4125)
	at java.base/java.lang.Class.annotationData(Class.java:4114)
	at java.base/java.lang.Class.getAnnotation(Class.java:3997)
	at java.base/java.lang.reflect.AnnotatedElement.isAnnotationPresent(AnnotatedElement.java:292)
	at java.base/java.lang.Class.isAnnotationPresent(Class.java:4007)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.descriptor_delegate$lambda$0(KClassImpl.kt:59)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.accessor$KClassImpl$Data$lambda0(KClassImpl.kt)
	at kotlin.reflect.jvm.internal.KClassImpl$Data$$Lambda$0.invoke(Unknown Source)
	at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:70)
	at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:32)
	at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt:53)
	at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:193)
	at kotlin.reflect.jvm.internal.KClassImpl.isValue(KClassImpl.kt:300)
	at io.mockk.impl.InternalPlatform.isValueClass(InternalPlatform.kt:65)
	at io.mockk.impl.InternalPlatform.packRef(InternalPlatform.kt:70)
	at io.mockk.impl.recording.ChainedCallDetector.detect$regularArgument(ChainedCallDetector.kt:47)
	at io.mockk.impl.recording.ChainedCallDetector.detect$detectArgMatchers(ChainedCallDetector.kt:113)
	at io.mockk.impl.recording.ChainedCallDetector.detect(ChainedCallDetector.kt:153)
	at io.mockk.impl.recording.SignatureMatcherDetector.detect(SignatureMatcherDetector.kt:91)
	at io.mockk.impl.recording.states.RecordingState.signMatchers(RecordingState.kt:39)
	at io.mockk.impl.recording.states.RecordingState.round(RecordingState.kt:31)
	at io.mockk.impl.recording.CommonCallRecorder.round(CommonCallRecorder.kt:50)
	at io.mockk.impl.eval.RecordedBlockEvaluator.record(RecordedBlockEvaluator.kt:62)
	at io.mockk.impl.eval.EveryBlockEvaluator.every(EveryBlockEvaluator.kt:30)
	at io.mockk.MockKDsl.internalCoEvery(API.kt:100)
	at io.mockk.MockKKt.coEvery(MockK.kt:169)
```

**Comment by languitar** [comment]
Weird, stacktracedecoroutinator isn't even included here, but the error only appears after the version bump.

**Comment by Anamorphosee** [comment]
Is it possible to add the snapshot repository in your `build.gradle.kts`
```
repositories {
    maven {
        url = uri("https://s01.oss.sonatype.org/content/repositories/snapshots/")
    }
}
```
And bump Decoroutinator version to `2.4.5-SNAPSHOT` to check if all the issues were fixed?

**Comment by languitar** [comment]
I can give that a try

**Comment by languitar** [comment]
Sorry, I'll only be able to test that on Monday

**Comment by languitar** [comment]
Sorry for the delay. The snapshot version results in different errors:

```
java.lang.NullPointerException: Cannot invoke "kotlinx.coroutines.flow.Flow.collect(kotlinx.coroutines.flow.FlowCollector, kotlin.coroutines.Continuation)" because "$this$single" is null
	at kotlinx.coroutines.flow.FlowKt__ReduceKt.single(Reduce.kt:53)
	at kotlinx.coroutines.flow.FlowKt.single(Unknown Source)
	at kotlinx.coroutines.flow.FlowKt__ReduceKt$single$1.invokeSuspend(Reduce.kt)
	at dev.reformator.stacktracedecoroutinator.common.internal.DecoroutinatorSpecImpl.resumeNext(utils-common.kt:156)
	at kotlinx.coroutines.flow.FlowKt.single(Unknown Source)
```

**Comment by Anamorphosee** [comment]
And please check it once more. The same version `1.4.5-SNAPSHOT` but with Gradle options `--refresh-dependencies` to force redownload a new version

**Comment by languitar** [comment]
Thanks, assuming you mean 2.4.5-SNAPSHOT, that version works in all of our tests.

**Comment by Anamorphosee** [comment]
Good. Then I'll make another release with all the fixes on this week

**Comment by languitar** [comment]
Thanks again!

**Comment by Anamorphosee** [comment]
released in 2.4.5
